/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RestrictionStatus {
    isRestricted: boolean;
    notified: boolean;
}
export interface ConversationItem {
    status: string;
    createdAt: bigint;
    sender: Principal;
    expirationSeconds: bigint;
    snapId: bigint;
}
export interface ChatListItem {
    isFriend: boolean;
    friendName: string;
    unviewedSnapCount: bigint;
    lastActivityType: string;
    friendUsername: string;
    unviewedSnapId?: bigint;
    friendPrincipal: Principal;
    lastActivityAt: bigint;
    streakAtRisk: boolean;
    streakCount: bigint;
}
export interface GroupView {
    id: bigint;
    members: Array<UserSearchResult>;
    name: string;
    createdAt: bigint;
}
export interface StreakView {
    isAtRisk: boolean;
    friendName: string;
    count: bigint;
    friendUsername: string;
    lastExchangeAt: bigint;
    friendPrincipal: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SnapViewResult {
    expirationSeconds: bigint;
    mediaBlob: ExternalBlob;
    mediaType: string;
}
export interface SentSnapItem {
    createdAt: bigint;
    viewedCount: bigint;
    snapId: bigint;
    recipientCount: bigint;
}
export interface FriendRequestView {
    id: bigint;
    principal: Principal;
    username: string;
    name: string;
    createdAt: bigint;
}
export interface StoryMediaResult {
    mediaBlob: ExternalBlob;
    mediaType: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    username: string;
    name: string;
}
export interface UserSearchResult {
    principal: Principal;
    username: string;
    name: string;
}
export interface StoryView {
    authorUsername: string;
    storyId: bigint;
    createdAt: bigint;
    authorName: string;
    author: Principal;
    mediaType: string;
}
export interface InboxItem {
    isViewed: boolean;
    createdAt: bigint;
    sender: Principal;
    expirationSeconds: bigint;
    snapId: bigint;
    senderName: string;
}
export interface FriendRequestsResult {
    incoming: Array<FriendRequestView>;
    outgoing: Array<FriendRequestView>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    acknowledgeRestriction(): Promise<void>;
    blockUser(target: Principal): Promise<void>;
    cancelFriendRequest(requestId: bigint): Promise<void>;
    checkUsernameAvailability(username: string): Promise<boolean>;
    createGroup(name: string, members: Array<Principal>): Promise<bigint>;
    deleteGroup(groupId: bigint): Promise<void>;
    deleteStory(storyId: bigint): Promise<void>;
    getBlockedUsers(): Promise<Array<UserSearchResult>>;
    getChatList(): Promise<Array<ChatListItem>>;
    getConversation(friend: Principal): Promise<Array<ConversationItem>>;
    getFriendRequests(): Promise<FriendRequestsResult>;
    getFriends(): Promise<Array<UserSearchResult>>;
    getFriendsStories(): Promise<Array<StoryView>>;
    getGroups(): Promise<Array<GroupView>>;
    getInbox(): Promise<Array<InboxItem>>;
    getMyReports(): Promise<Array<Principal>>;
    getMyStories(): Promise<Array<StoryView>>;
    getProfile(): Promise<Profile | null>;
    getRestrictionStatus(): Promise<RestrictionStatus>;
    getSentSnaps(): Promise<Array<SentSnapItem>>;
    getStoryMedia(storyId: bigint): Promise<StoryMediaResult>;
    getStreaks(): Promise<Array<StreakView>>;
    postStory(mediaBlob: ExternalBlob, mediaType: string): Promise<void>;
    reportUser(target: Principal): Promise<void>;
    respondToFriendRequest(requestId: bigint, accept: boolean): Promise<void>;
    searchUsers(prefix: string): Promise<Array<UserSearchResult>>;
    sendFriendRequest(to: Principal): Promise<void>;
    sendSnap(recipients: Array<Principal>, mediaBlob: ExternalBlob, mediaType: string, expirationSeconds: bigint): Promise<void>;
    setProfile(name: string, username: string): Promise<void>;
    unblockUser(target: Principal): Promise<void>;
    unfriend(target: Principal): Promise<void>;
    updateGroup(groupId: bigint, name: string, members: Array<Principal>): Promise<void>;
    viewSnap(snapId: bigint): Promise<SnapViewResult>;
    withdrawReport(target: Principal): Promise<void>;
}
import type { ChatListItem as _ChatListItem, ExternalBlob as _ExternalBlob, Profile as _Profile, SnapViewResult as _SnapViewResult, StoryMediaResult as _StoryMediaResult, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async acknowledgeRestriction(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeRestriction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeRestriction();
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async cancelFriendRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelFriendRequest(arg0);
            return result;
        }
    }
    async checkUsernameAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailability(arg0);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: Array<Principal>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async deleteGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async deleteStory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async getBlockedUsers(): Promise<Array<UserSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getChatList(): Promise<Array<ChatListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatList();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatList();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<ConversationItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getFriendRequests(): Promise<FriendRequestsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return result;
        }
    }
    async getFriends(): Promise<Array<UserSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getFriendsStories(): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsStories();
            return result;
        }
    }
    async getGroups(): Promise<Array<GroupView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroups();
            return result;
        }
    }
    async getInbox(): Promise<Array<InboxItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return result;
        }
    }
    async getMyReports(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReports();
            return result;
        }
    }
    async getMyStories(): Promise<Array<StoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStories();
            return result;
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestrictionStatus(): Promise<RestrictionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestrictionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestrictionStatus();
            return result;
        }
    }
    async getSentSnaps(): Promise<Array<SentSnapItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentSnaps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentSnaps();
            return result;
        }
    }
    async getStoryMedia(arg0: bigint): Promise<StoryMediaResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryMedia(arg0);
                return from_candid_StoryMediaResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryMedia(arg0);
            return from_candid_StoryMediaResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreaks(): Promise<Array<StreakView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreaks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreaks();
            return result;
        }
    }
    async postStory(arg0: ExternalBlob, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postStory(await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postStory(await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async reportUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0);
            return result;
        }
    }
    async respondToFriendRequest(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToFriendRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToFriendRequest(arg0, arg1);
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async sendSnap(arg0: Array<Principal>, arg1: ExternalBlob, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSnap(arg0, await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSnap(arg0, await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async setProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unfriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfriend(arg0);
            return result;
        }
    }
    async updateGroup(arg0: bigint, arg1: string, arg2: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async viewSnap(arg0: bigint): Promise<SnapViewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.viewSnap(arg0);
                return from_candid_SnapViewResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewSnap(arg0);
            return from_candid_SnapViewResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async withdrawReport(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawReport(arg0);
            return result;
        }
    }
}
function from_candid_ChatListItem_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatListItem): ChatListItem {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_SnapViewResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SnapViewResult): Promise<SnapViewResult> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_StoryMediaResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryMediaResult): Promise<StoryMediaResult> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isFriend: boolean;
    friendName: string;
    unviewedSnapCount: bigint;
    lastActivityType: string;
    friendUsername: string;
    unviewedSnapId: [] | [bigint];
    friendPrincipal: Principal;
    lastActivityAt: bigint;
    streakAtRisk: boolean;
    streakCount: bigint;
}): {
    isFriend: boolean;
    friendName: string;
    unviewedSnapCount: bigint;
    lastActivityType: string;
    friendUsername: string;
    unviewedSnapId?: bigint;
    friendPrincipal: Principal;
    lastActivityAt: bigint;
    streakAtRisk: boolean;
    streakCount: bigint;
} {
    return {
        isFriend: value.isFriend,
        friendName: value.friendName,
        unviewedSnapCount: value.unviewedSnapCount,
        lastActivityType: value.lastActivityType,
        friendUsername: value.friendUsername,
        unviewedSnapId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.unviewedSnapId)),
        friendPrincipal: value.friendPrincipal,
        lastActivityAt: value.lastActivityAt,
        streakAtRisk: value.streakAtRisk,
        streakCount: value.streakCount
    };
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mediaBlob: _ExternalBlob;
    mediaType: string;
}): Promise<{
    mediaBlob: ExternalBlob;
    mediaType: string;
}> {
    return {
        mediaBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.mediaBlob),
        mediaType: value.mediaType
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expirationSeconds: bigint;
    mediaBlob: _ExternalBlob;
    mediaType: string;
}): Promise<{
    expirationSeconds: bigint;
    mediaBlob: ExternalBlob;
    mediaType: string;
}> {
    return {
        expirationSeconds: value.expirationSeconds,
        mediaBlob: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.mediaBlob),
        mediaType: value.mediaType
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatListItem>): Array<ChatListItem> {
    return value.map((x)=>from_candid_ChatListItem_n9(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
