/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatListItem {
  'isFriend' : boolean,
  'friendName' : string,
  'unviewedSnapCount' : bigint,
  'lastActivityType' : string,
  'friendUsername' : string,
  'unviewedSnapId' : [] | [bigint],
  'friendPrincipal' : Principal,
  'lastActivityAt' : bigint,
  'streakAtRisk' : boolean,
  'streakCount' : bigint,
}
export interface ConversationItem {
  'status' : string,
  'createdAt' : bigint,
  'sender' : Principal,
  'expirationSeconds' : bigint,
  'snapId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FriendRequestView {
  'id' : bigint,
  'principal' : Principal,
  'username' : string,
  'name' : string,
  'createdAt' : bigint,
}
export interface FriendRequestsResult {
  'incoming' : Array<FriendRequestView>,
  'outgoing' : Array<FriendRequestView>,
}
export interface GroupView {
  'id' : bigint,
  'members' : Array<UserSearchResult>,
  'name' : string,
  'createdAt' : bigint,
}
export interface InboxItem {
  'isViewed' : boolean,
  'createdAt' : bigint,
  'sender' : Principal,
  'expirationSeconds' : bigint,
  'snapId' : bigint,
  'senderName' : string,
}
export interface Profile { 'username' : string, 'name' : string }
export interface RestrictionStatus {
  'isRestricted' : boolean,
  'notified' : boolean,
}
export interface SentSnapItem {
  'createdAt' : bigint,
  'viewedCount' : bigint,
  'snapId' : bigint,
  'recipientCount' : bigint,
}
export interface SnapViewResult {
  'expirationSeconds' : bigint,
  'mediaBlob' : ExternalBlob,
  'mediaType' : string,
}
export interface StoryMediaResult {
  'mediaBlob' : ExternalBlob,
  'mediaType' : string,
}
export interface StoryView {
  'authorUsername' : string,
  'storyId' : bigint,
  'createdAt' : bigint,
  'authorName' : string,
  'author' : Principal,
  'mediaType' : string,
}
export interface StreakView {
  'isAtRisk' : boolean,
  'friendName' : string,
  'count' : bigint,
  'friendUsername' : string,
  'lastExchangeAt' : bigint,
  'friendPrincipal' : Principal,
}
export interface UserSearchResult {
  'principal' : Principal,
  'username' : string,
  'name' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'acknowledgeRestriction' : ActorMethod<[], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'cancelFriendRequest' : ActorMethod<[bigint], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createGroup' : ActorMethod<[string, Array<Principal>], bigint>,
  'deleteGroup' : ActorMethod<[bigint], undefined>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'getBlockedUsers' : ActorMethod<[], Array<UserSearchResult>>,
  'getChatList' : ActorMethod<[], Array<ChatListItem>>,
  'getConversation' : ActorMethod<[Principal], Array<ConversationItem>>,
  'getFriendRequests' : ActorMethod<[], FriendRequestsResult>,
  'getFriends' : ActorMethod<[], Array<UserSearchResult>>,
  'getFriendsStories' : ActorMethod<[], Array<StoryView>>,
  'getGroups' : ActorMethod<[], Array<GroupView>>,
  'getInbox' : ActorMethod<[], Array<InboxItem>>,
  'getMyReports' : ActorMethod<[], Array<Principal>>,
  'getMyStories' : ActorMethod<[], Array<StoryView>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getRestrictionStatus' : ActorMethod<[], RestrictionStatus>,
  'getSentSnaps' : ActorMethod<[], Array<SentSnapItem>>,
  'getStoryMedia' : ActorMethod<[bigint], StoryMediaResult>,
  'getStreaks' : ActorMethod<[], Array<StreakView>>,
  'postStory' : ActorMethod<[ExternalBlob, string], undefined>,
  'reportUser' : ActorMethod<[Principal], undefined>,
  'respondToFriendRequest' : ActorMethod<[bigint, boolean], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserSearchResult>>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendSnap' : ActorMethod<
    [Array<Principal>, ExternalBlob, string, bigint],
    undefined
  >,
  'setProfile' : ActorMethod<[string, string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unfriend' : ActorMethod<[Principal], undefined>,
  'updateGroup' : ActorMethod<[bigint, string, Array<Principal>], undefined>,
  'viewSnap' : ActorMethod<[bigint], SnapViewResult>,
  'withdrawReport' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];